select * from INTERNSHIP;

Drop table STUDENT
Drop table INTERNSHIP

create table STUDENT
(
   S_ID VARCHAR(20) NOT NULL PRIMARY KEY,
   NAME VARCHAR(500) NOT NULL,
   GENDER TEXT CHECK (GENDER IN ('Male' , 'Female')) NOT NULL,
   ContactNum VARCHAR(12) NOT NULL,
   PersonalEmail VARCHAR(100) UNIQUE,
   CollegeEmail VARCHAR(100) NOT NULL,
   YEAR VARCHAR(10) NOT NULL,
   SEMESTER VARCHAR(10) NOT NULL

);

-
select * from FACULTY

CREATE TABLE FACULTY
(
    F_ID VARCHAR(20),
    F_NAME VARCHAR(255) NOT NULL,
    FMAIL VARCHAR(255) UNIQUE
);



CREATE TABLE INTERNSHIP
(
    INTERNSHIP_ID SERIAL,
    STUDENT_ID VARCHAR REFERENCES STUDENT(S_ID),
    INTERNSHIP_NAME VARCHAR(255) NOT NULL,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    INTERNSHIP_START_DATE DATE,
    INTERNSHIP_END_DATE DATE,
    STIPEND DECIMAL(10, 2),
    CERTIFICATE_PHOTO BYTEA
   
);



